In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# EDA

In [2]:
df=pd.read_csv('spam.csv',encoding='latin-1')

In [3]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df.shape

(5572, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

# Text Preprocessing

In [6]:
cols=['Unnamed: 2','Unnamed: 3','Unnamed: 4']
df=df.drop(cols,axis=1)

In [7]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df=df.rename(columns={
    'v1' : "types",
    'v2' : "sms"
})

In [9]:
df.head()

  types                                                sms
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.isna().sum()

types    0
sms      0
dtype: int64

In [11]:
df['types'].unique()

array(['ham', 'spam'], dtype=object)

In [12]:
df['types']=df['types'].map({
    "ham" : 0,
    "spam" : 1
})

In [13]:
df.head()

   types                                                sms
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [14]:
df['sms']=df['sms'].astype(str).str.lower()

In [15]:
df.head()

   types                                                sms
0      0  go until jurong point, crazy.. available only ...
1      0                      ok lar... joking wif u oni...
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0  u dun say so early hor... u c already then say...
4      0  nah i don't think he goes to usf, he lives aro...

In [16]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [17]:
df['sms']=df['sms'].apply(remove_punc)

In [18]:
df.head()

   types                                                sms
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...

In [19]:
def remove_num(txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new=new+i
    return new
df['sms']=df['sms'].apply(remove_num)

In [20]:
df.head()

   types                                                sms
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in  a wkly comp to win fa cup final...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...

In [21]:
def remove_url(txt):
    new=""
    for i in txt:
        if i!="//" or i!="https" or i!=":":
            new=new+i
    return new
df['sms']=df['sms'].apply(remove_url)

In [22]:
df

      types                                                sms
0         0  go until jurong point crazy available only in ...
1         0                            ok lar joking wif u oni
2         1  free entry in  a wkly comp to win fa cup final...
3         0        u dun say so early hor u c already then say
4         0  nah i dont think he goes to usf he lives aroun...
...     ...                                                ...
5567      1  this is the nd time we have tried  contact u u...
5568      0                will ì b going to esplanade fr home
5569      0  pity  was in mood for that soany other suggest...
5570      0  the guy did some bitching but i acted like id ...
5571      0                          rofl its true to its name

[5572 rows x 2 columns]

# Tokenization and Stopword Removal

In [23]:
import nltk

In [24]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [25]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\anush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
stop_words=set(stopwords.words('english'))

In [27]:
def remove(txt):
    words=word_tokenize(txt)
    cleaned=[]
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)
df['sms']=df['sms'].apply(remove)

In [28]:
df.head()

   types                                                sms
0      0  go jurong point crazy available bugis n great ...
1      0                            ok lar joking wif u oni
2      1  free entry wkly comp win fa cup final tkts st ...
3      0                u dun say early hor u c already say
4      0        nah dont think goes usf lives around though

# Model Selection

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(df['sms'], df['types'], test_size=0.20, random_state=42)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

### Multinomial Naive Bayes

In [32]:
from sklearn.naive_bayes import MultinomialNB

In [33]:
mnb_model=MultinomialNB()

In [34]:
mnb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [35]:
y_pred=mnb_model.predict(X_test_bow)

In [36]:
from sklearn.metrics import accuracy_score
acc_mnb=accuracy_score(y_test,y_pred)
print(acc_mnb)

0.9802690582959641

### Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
lr_model=LogisticRegression()
lr_model.fit(X_train_bow,y_train)

LogisticRegression()

In [55]:
y_pred_lr=lr_model.predict(X_test_bow)
acc_lr=accuracy_score(y_test,y_pred_lr)
print(acc_lr)

0.9766816143497757

### KNN

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier()

In [41]:
knn_model.fit(X_train_bow,y_train)
y_pred_knn=knn_model.predict(X_test_bow)
acc_knn=accuracy_score(y_test,y_pred_knn)
print(acc_knn)

0.9219730941704036

# Support Vector Machine

In [42]:
from sklearn.svm import SVC

In [43]:
svc_model=SVC()
svc_model.fit(X_train_bow,y_train)

SVC()

In [44]:
svc_model.fit(X_train_bow,y_train)
y_pred_svc=svc_model.predict(X_test_bow)
acc_svc=accuracy_score(y_test,y_pred_svc)
print(acc_svc)

0.9766816143497757

### Decision Tree

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train_bow,y_train)

DecisionTreeClassifier()

In [47]:
dt_model.fit(X_train_bow,y_train)
y_pred_dt=dt_model.predict(X_test_bow)
acc_dt=accuracy_score(y_test,y_pred_dt)
print(acc_dt)

0.9623318385650225

### Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
rtc_model=RandomForestClassifier()
rtc_model.fit(X_train_bow,y_train)

RandomForestClassifier()

In [50]:
rtc_model.fit(X_train_bow,y_train)
y_pred_rtc=rtc_model.predict(X_test_bow)
acc_rtc=accuracy_score(y_test,y_pred_rtc)
print(acc_rtc)

0.9704035874439462

# Results

In [53]:
result = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Support Vector Machine",
        "Multinomial Naive Bayes",
        "KNN",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        round(acc_lr, 3),
        round(acc_svc, 3),
        round(acc_mnb, 3),
        round(acc_knn, 3),
        round(acc_dt, 3),
        round(acc_rtc, 3)
    ]})
result

                     Model  Accuracy
0      Logistic Regression     0.977
1   Support Vector Machine     0.977
2  Multinomial Naive Bayes     0.980
3                      KNN     0.922
4            Decision Tree     0.962
5            Random Forest     0.970

# Final Decision

#### Multinomial Naive Bayes achieved the highest accuracy of 98.0% among the tested models and was selected as the final model for SMS spam classification.